config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path("grappelli/", include("grappelli.urls")),  # grappelli URLS
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("shokrnet.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("ip_manager/", include("shokrnet.ip_manager.urls", namespace="ip_manager")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router", namespace="api")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns
######################################################################
admin.site.site_header = "Shokr Net"
admin.site.site_title = " IP management"
admin.site.index_title = " IP management Admin"
#######################################################################

shokrnet/ip_manager/urls.py
from django.urls import path

from .views import *

app_name = "ip_manager"

urlpatterns = [
    path("", home, name="home"),
    path("ip/", IPListView.as_view(), name="list_ip"),
    path("ip/add/", IPCreate.as_view(), name="add_ip"),
    path("ip/update/<int:pk>/", IPUpdate.as_view(), name="update_ip"),
    path("ip/<int:pk>/", IPDetailView.as_view(), name="detail_ip"),
    path("ip/delete/<int:pk>/", delete_ip, name="delete_ip"),
    path("subnet/", SubnetListView.as_view(), name="list_subnet"),
    path("subnet/add/", SubnetCreate.as_view(), name="add_subnet"),
    path("subnet/update/<int:pk>/", SubnetUpdate.as_view(), name="update_subnet"),
    path("subnet/<int:pk>/", SubnetDetailView.as_view(), name="detail_subnet"),
    path("subnet/delete/<int:pk>/", delete_subnet, name="delete_subnet"),
    path("subnet/ip_list/<int:pk>/", subnet_ips, name="subnet_ips"),
    path("vlan/", VLANListView.as_view(), name="list_vlan"),
    path("vlan/add/", VLANCreate.as_view(), name="add_vlan"),
    path("vlan/update/<int:pk>/", VLANUpdate.as_view(), name="update_vlan"),
    path("vlan/<int:pk>/", VLANDetailView.as_view(), name="detail_vlan"),
    path("vlan/delete/<int:pk>/", delete_VLAN, name="delete_vlan"),
    #
    path("service/", ServiceListView.as_view(), name="list_service"),
    path("service/add/", ServiceCreate.as_view(), name="add_service"),
    path("service/update/<int:pk>/", ServiceUpdate.as_view(), name="update_service"),
    path("service/<int:pk>/", ServiceDetailView.as_view(), name="detail_service"),
    path("service/delete/<int:pk>/", delete_Service, name="delete_service"),
    path("device/", DeviceListView.as_view(), name="list_device"),
    path("device/add/", DeviceCreate.as_view(), name="add_device"),
    path("device/update/<int:pk>/", DeviceUpdate.as_view(), name="update_device"),
    path("device/<int:pk>/", DeviceDetailView.as_view(), name="detail_device"),
    path("device/delete/<int:pk>/", delete_Device, name="delete_device"),
    path("deviceType/", DeviceTypeListView.as_view(), name="list_device_type"),
    path("deviceType/add/", DeviceTypeCreate.as_view(), name="add_device_type"),
    path(
        "deviceType/update/<int:pk>/",
        DeviceTypeUpdate.as_view(),
        name="update_device_type",
    ),
    path(
        "deviceType/<int:pk>/",
        DeviceTypeDetailView.as_view(),
        name="detail_device_type",
    ),
    path("deviceType/delete/<int:pk>/", delete_DeviceType, name="delete_device_type"),
    path("location/", LocationListView.as_view(), name="list_location"),
    path("location/add/", LocationCreate.as_view(), name="add_location"),
    path("location/update/<int:pk>/", LocationUpdate.as_view(), name="update_location"),
    path("location/<int:pk>/", LocationDetailView.as_view(), name="detail_location"),
    path("location/delete/<int:pk>/", delete_Location, name="delete_location"),
    # # # EXPORTING
    # path('ip/csv', exportIPCSV, name='IPCSV'),
    # path('ip/json', exportIPJSON, name='IPJSON'),
    # path('ip/xls', exportIPXLS, name='IPXLS'),
]

# path('delete/<int:pk>/', IPDelete.as_view(), name='delete_ip'),

shokrnet/users/urls.py
from django.urls import path

from shokrnet.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

shokrnet/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):
    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

shokrnet/ip_manager/forms.py
from django import forms

from .models import *


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = "__all__"


class DeviceTypeForm(forms.ModelForm):
    class Meta:
        model = DeviceType
        fields = "__all__"


class DeviceForm(forms.ModelForm):
    class Meta:
        model = Device
        fields = "__all__"


class SubnetForm(forms.ModelForm):
    class Meta:
        model = Subnet
        fields = "__all__"


class IPForm(forms.ModelForm):
    class Meta:
        model = IPAddress
        fields = "__all__"


class VLANForm(forms.ModelForm):
    class Meta:
        model = VLAN
        fields = "__all__"


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = "__all__"

shokrnet/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):
    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

shokrnet/ip_manager/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView

from shokrnet.ip_manager.forms import *


@login_required
def home(request):
    location = Location.objects.get_queryset().count()
    subnet = Subnet.objects.get_queryset().count()
    ip = IPAddress.objects.get_queryset().count()
    service = Service.objects.get_queryset().count()
    device = Device.objects.get_queryset().count()
    deviceType = DeviceType.objects.get_queryset().count()
    vlan = VLAN.objects.get_queryset().count()

    user = request.user

    return render(
        request,
        "ip_manager/home",
        {
            "user": user,
            "location": location,
            "subnet": subnet,
            "ip": ip,
            "service": service,
            "device": device,
            "device_type": deviceType,
            "vlan": vlan,
        },
    )


# IP


class IPCreate(CreateView):
    model = IPAddress
    fields = [
        "subnet",
        "address",
        "status",
        "role",
        "device",
        "nat_inside",
        "dns_name",
        "description",
    ]

    def get_success_url(self):
        return reverse("ip_manager:list_ip")


class IPUpdate(UpdateView):
    model = IPAddress
    fields = [
        "subnet",
        "address",
        "status",
        "role",
        "device",
        "nat_inside",
        "dns_name",
        "description",
    ]


class IPDetailView(DetailView):
    model = IPAddress


class IPListView(ListView):
    model = IPAddress
    # paginate_by = 50


@login_required
def delete_ip(request, pk):
    ip = get_object_or_404(IPAddress, pk=pk)
    subnet = ip.subnet.pk
    reserved_hosts = Subnet.objects.get(pk=subnet).reserved_hosts
    total_hosts = Subnet.objects.get(pk=subnet).total_hosts
    Subnet.objects.filter(pk=subnet).update(
        reserved_hosts=reserved_hosts - 1,
        utilization_percentage=(reserved_hosts / total_hosts) * 100,
    )
    ip.delete()
    return redirect("ip_manager:list_ip")


# Subnet


class SubnetCreate(CreateView):
    model = Subnet
    fields = ["name", "subnet", "description", "master_subnet", "vlan"]


class SubnetUpdate(UpdateView):
    model = Subnet
    fields = ["name", "subnet", "description", "master_subnet", "vlan"]


class SubnetDetailView(DetailView):
    model = Subnet


class SubnetListView(ListView):
    model = Subnet


@login_required
def delete_subnet(request, pk):
    subnet = get_object_or_404(Subnet, pk=pk)
    subnet.delete()
    return redirect("ip_manager:list_subnet")


# VLAN


class VLANCreate(CreateView):
    model = VLAN
    fields = ["name", "location", "vid", "status", "description"]


class VLANUpdate(UpdateView):
    model = VLAN
    fields = ["name", "location", "vid", "status", "description"]


class VLANDetailView(DetailView):
    model = VLAN


class VLANListView(ListView):
    model = VLAN


@login_required
def delete_VLAN(request, pk):
    vlan = get_object_or_404(VLAN, pk=pk)
    vlan.delete()
    return redirect("ip_manager:list_vlan")


# Service


class ServiceCreate(CreateView):
    model = Service
    fields = ["name", "protocol", "ip_addresses", "port", "description"]


class ServiceUpdate(UpdateView):
    model = Service
    fields = ["name", "protocol", "ip_addresses", "port", "description"]


class ServiceDetailView(DetailView):
    model = Service


class ServiceListView(ListView):
    model = Service


@login_required
def delete_Service(request, pk):
    service = get_object_or_404(Service, pk=pk)
    service.delete()
    return redirect("ip_manager:list_service")


# Device


class DeviceCreate(CreateView):
    model = Device
    fields = ["name", "serial_number", "mac", "device_type"]


class DeviceUpdate(UpdateView):
    model = Device
    fields = ["name", "serial_number", "mac", "device_type"]


class DeviceDetailView(DetailView):
    model = Device


class DeviceListView(ListView):
    model = Device


@login_required
def delete_Device(request, pk):
    device = get_object_or_404(Device, pk=pk)
    device.delete()
    return redirect("ip_manager:list_device")


# Device Type


class DeviceTypeCreate(CreateView):
    model = DeviceType
    fields = ["manufacturer", "model_number", "name"]


class DeviceTypeUpdate(UpdateView):
    model = DeviceType
    fields = ["manufacturer", "model_number", "name"]


class DeviceTypeDetailView(DetailView):
    model = DeviceType


class DeviceTypeListView(ListView):
    model = DeviceType


@login_required
def delete_DeviceType(request, pk):
    device_type = get_object_or_404(DeviceType, pk=pk)
    device_type.delete()
    return redirect("ip_manager:list_device_type")


# Location


class LocationCreate(CreateView):
    model = Location
    fields = ["name", "geolocation", "address"]


class LocationUpdate(UpdateView):
    model = Location
    fields = ["name", "geolocation", "address"]


class LocationDetailView(DetailView):
    model = Location


class LocationListView(ListView):
    model = Location


@login_required
def delete_Location(request, pk):
    location = get_object_or_404(Location, pk=pk)
    location.delete()
    return redirect("ip_manager:list_location")


@login_required
def subnet_ips(request, pk):
    subnet = get_object_or_404(Subnet, pk=pk)
    used_ips = IPAddress.objects.filter(subnet=subnet).values_list("address", flat=True)
    ip_list = list(ipaddress.ip_network(subnet.subnet).hosts())
    free_ips = list(set(ip_list) - set(used_ips))

    return render(
        request,
        "ip_manager/subnet_ip_list.html",
        {"subnet": subnet, "usedIPS": used_ips, "freeIPS": free_ips},
    )


#######################################################################################################################
#

# class IPDelete(DeleteView):
#     model = IPAddress
#     success_url = reverse_lazy('ip_manager:home')
#
#
# @login_required
# def exportIPCSV(request):
#     resource = IPResource()
#     dataset = resource.export()
#     response = HttpResponse(dataset.csv, content_type='text/csv')
#     response['Content-Disposition'] = 'attachment; filename="network_IPs.csv"'
#     return response
#
#
# @login_required
# def exportIPJSON(request):
#     resource = IPResource()
#     dataset = resource.export()
#     response = HttpResponse(dataset.json, content_type='application/json')
#     response['Content-Disposition'] = 'attachment; filename="network_IPs.json"'
#     return response
#
#
# @login_required
# def exportIPXLS(request):
#     resource = IPResource()
#     dataset = resource.export()
#     response = HttpResponse(dataset.xls, content_type='application/vnd.ms-excel')
#     response['Content-Disposition'] = 'attachment; filename="network_IPs.xls"'
#     return response

shokrnet/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

shokrnet/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

shokrnet/templates/ip_manager/device_list.html
{% extends "base.html" %}
{% load static %}

{% block title %} Device List {% endblock %}

{% block content %}
  <br/>

  <div class="container">
    <div class="row justify-content-center">
      <a class="btn btn-lg btn-outline-success" href="{% url 'ip_manager:add_device' %}"> Add Device </a>
    </div>
  </div>


  <!-- Main Content -->
  <div class="container">

    <table id="table" class="table table-striped table-bordered" style="width:100%"
           data-toggle="table" data-pagination="true"
           data-search="true" data-show-columns="true"
           data-show-pagination-switch="true" data-show-refresh="true"
           data-show-toggle="true"
           data-resizable="true"
           data-toolbar="#toolbar">
      <thead>
      <tr>
        <th>Name</th>
        <th>Serial Number</th>
        <th>MAC</th>
        <th>Device Type</th>
        <th>Actions</th>
      </tr>
      </thead>

      <tbody>

      {% for obj in object_list %}
        <tr>

          <td>
            <a href="{% url 'ip_manager:detail_device' obj.pk %}">
              {{ obj.name }}
            </a>
          </td>

          <td> {{ obj.serial_number }}</td>
          <td> {{ obj.mac }}</td>
          <td> {{ obj.device_type }}</td>

          <td>
            <a href="{% url 'ip_manager:update_device' obj.pk %}"><i class="fa fa-edit"></i></a>
            &nbsp;&nbsp;
            <a href="{% url 'ip_manager:delete_device' obj.pk %}"><i class="fa fa-trash"></i></a>
          </td>

        </tr>

      {% endfor %}


      </tbody>
    </table>

  </div>

{% endblock content %}

shokrnet/templates/ip_manager/devicetype_detail.html
{% extends 'base.html' %}


{% block content %}
  <br>
  <div class="container">
    <div class="row justify-content-center">

      <div class="card" style="width: 18rem;">
        {#                <img class="card-img-top" src="..." alt="Card image cap">#}
        <div class="card-body">
          <h5 class="card-title" style="color: #0A246A">{{ object.name }}</h5>
          <hr>
        </div>
        <ul class="list-group list-group-flush">

          <li class="list-group-item">Model Number: <span style="font-weight: bolder;">{{ object.model_number }}</span>
          </li>
          <li class="list-group-item">Manufacturer: <span style="font-weight: bolder;">{{ object.manufacturer }}</span>
          </li>
          </li>


          <li class="list-group-item">Created at: <span
                  style="font-weight: bolder;">{{ object.time_created|date }}</span></li>

          <li class="list-group-item">
            <a class="btn btn-sm btn-outline-warning"
               href="{% url 'ip_manager:update_device_type' object.pk %}"> Edit </a>

            <a class="btn btn-sm btn-outline-danger"
               href="{% url 'ip_manager:delete_device_type' object.pk %}"> Delete </a>
          </li>

        </ul>

      </div>
    </div>
  </div>

{% endblock %}

shokrnet/templates/ip_manager/ipaddress_detail.html
{% extends 'base.html' %}


{% block content %}
  <br>
  <div class="container">
    <div class="row justify-content-center">

      <div class="card" style="width: 18rem;">
        {#                <img class="card-img-top" src="..." alt="Card image cap">#}
        <div class="card-body">
          <h5 class="card-title" style="color: #0A246A">{{ object.address }}</h5>
          <hr>
          <p class="card-text">
          <h6 style="color: #761c19; font-weight: bolder">Subnet:</h6>
          {{ object.subnet }}
          </p>
        </div>
        <ul class="list-group list-group-flush">

          <li class="list-group-item">Status: <span style="font-weight: bolder;">{{ object.status }}</span></li>
          <li class="list-group-item">Role: <span style="font-weight: bolder;">{{ object.role }}</span></li>
          <li class="list-group-item">Device: <span style="font-weight: bolder;">{{ object.device }}</span></li>
          <li class="list-group-item">NAT: <span style="font-weight: bolder;">{{ object.nat_inside }}</span></li>
          <li class="list-group-item">DNS: <span style="font-weight: bolder;">{{ object.dns_name }}</span></li>
          <li class="list-group-item">Description: <span style="font-weight: bolder;">{{ object.description }}</span>
          </li>


          <li class="list-group-item">Created at: <span
                  style="font-weight: bolder;">{{ object.time_created|date }}</span></li>

          <li class="list-group-item">
            <a class="btn btn-sm btn-outline-warning"
               href="{% url 'ip_manager:update_ip' object.pk %}"> Edit </a>

            <a class="btn btn-sm btn-outline-danger"
               href="{% url 'ip_manager:delete_ip' object.pk %}"> Delete </a>
          </li>

        </ul>

      </div>
    </div>
  </div>

{% endblock %}

shokrnet/templates/ip_manager/ipaddress_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <br/>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 col-sm-12 mx-auto">
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>
  <br/>
{% endblock %}

shokrnet/templates/ip_manager/ipaddress_list.html
{% extends "base.html" %}
{% load static %}

{% block title %} IP List {% endblock %}

{% block content %}

  <br/>

  <div class="container">
    <div class="row justify-content-center">
      <a class="btn btn-lg btn-outline-success" href="{% url 'ip_manager:add_ip' %}"> Add IP </a>
    </div>
  </div>


  <!-- Main Content -->
  <div class="container">

    <table id="table" class="table table-striped table-bordered" style="width:100%"
           data-toggle="table" data-pagination="true"
           data-search="true" data-show-columns="true"
           data-show-pagination-switch="true" data-show-refresh="true"
           data-show-toggle="true"
           data-resizable="true"
           data-toolbar="#toolbar">
      <thead>
      <tr>
        <th>IP</th>
        <th>Subnet</th>
        <th>Status</th>
        <th>Role</th>
        <th>Device</th>
        <th>NAT</th>
        <th>DNS</th>
        <th>Actions</th>
      </tr>
      </thead>

      <tbody>

      {% for obj in object_list %}
        <tr>
          <td>
            <a href="{% url 'ip_manager:detail_ip' obj.pk %}">
              {{ obj.address }}
            </a>
          </td>
          <td> {{ obj.subnet }}</td>
          <td> {{ obj.status }} </td>
          <td> {{ obj.role }}</td>
          <td> {{ obj.device }}</td>
          <td> {{ obj.nat_inside }}</td>
          <td> {{ obj.dns_name }}</td>

          <td>
            <a href="{% url 'ip_manager:update_ip' obj.pk %}"><i class="fa fa-edit"></i></a>
            &nbsp;&nbsp;
            <a href="{% url 'ip_manager:delete_ip' obj.pk %}"><i class="fa fa-trash"></i></a>
          </td>

        </tr>

      {% endfor %}


      </tbody>
    </table>

  </div>

{% endblock content %}

shokrnet/templates/ip_manager/location_list.html
{% extends "base.html" %}
{% load static %}

{% block title %} Location List {% endblock %}

{% block content %}
  <br/>

  <div class="container">
    <div class="row justify-content-center">
      <a class="btn btn-lg btn-outline-success" href="{% url 'ip_manager:add_location' %}"> Add Location </a>
    </div>
  </div>


  <!-- Main Content -->
  <div class="container">

    <table id="table" class="table table-striped table-bordered" style="width:100%"
           data-toggle="table" data-pagination="true"
           data-search="true" data-show-columns="true"
           data-show-pagination-switch="true" data-show-refresh="true"
           data-show-toggle="true"
           data-resizable="true"
           data-toolbar="#toolbar">
      <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Geolocation</th>
        <th>Actions</th>
      </tr>
      </thead>

      <tbody>

      {% for obj in object_list %}
        <tr>

          <td>
            <a href="{% url 'ip_manager:detail_location' obj.pk %}">
              {{ obj.name }}
            </a>
          </td>

          <td> {{ obj.address }}</td>
          <td> {{ obj.geolocation }}</td>

          <td>
            <a href="{% url 'ip_manager:update_location' obj.pk %}"><i class="fa fa-edit"></i></a>
            &nbsp;&nbsp;
            <a href="{% url 'ip_manager:delete_location' obj.pk %}"><i class="fa fa-trash"></i></a>
          </td>

        </tr>

      {% endfor %}


      </tbody>
    </table>

  </div>

{% endblock content %}

shokrnet/templates/ip_manager/service_list.html
{% extends "base.html" %}
{% load static %}

{% block title %} Service List {% endblock %}

{% block content %}
  <br/>

  <div class="container">
    <div class="row justify-content-center">
      <a class="btn btn-lg btn-outline-success" href="{% url 'ip_manager:add_service' %}"> Add Service </a>
    </div>
  </div>


  <!-- Main Content -->
  <div class="container">

    <table id="table" class="table table-striped table-bordered" style="width:100%"
           data-toggle="table" data-pagination="true"
           data-search="true" data-show-columns="true"
           data-show-pagination-switch="true" data-show-refresh="true"
           data-show-toggle="true"
           data-resizable="true"
           data-toolbar="#toolbar">
      <thead>
      <tr>
        <th>Name</th>
        <th>Protocol</th>
        <th>Port</th>
        {#        <th>IP Addresses</th>#}
        <th>Actions</th>
      </tr>
      </thead>

      <tbody>

      {% for obj in object_list %}
        <tr>

          <td>
            <a href="{% url 'ip_manager:detail_service' obj.pk %}">
              {{ obj.name }}
            </a>
          </td>

          <td> {{ obj.protocol }}</td>
          <td> {{ obj.port }}</td>
          {#          <td> {{ obj.ip_addresses }}</td>#}

          <td>
            <a href="{% url 'ip_manager:update_service' obj.pk %}"><i class="fa fa-edit"></i></a>
            &nbsp;&nbsp;
            <a href="{% url 'ip_manager:delete_service' obj.pk %}"><i class="fa fa-trash"></i></a>
          </td>

        </tr>

      {% endfor %}


      </tbody>
    </table>

  </div>

{% endblock content %}

shokrnet/templates/ip_manager/vlan_list.html
{% extends "base.html" %}
{% load static %}

{% block title %} VLAN List {% endblock %}

{% block content %}
  <br/>

  <div class="container">
    <div class="row justify-content-center">
      <a class="btn btn-lg btn-outline-success" href="{% url 'ip_manager:add_vlan' %}"> Add VLAN </a>
    </div>
  </div>


  <!-- Main Content -->
  <div class="container">

    <table id="table" class="table table-striped table-bordered" style="width:100%"
           data-toggle="table" data-pagination="true"
           data-search="true" data-show-columns="true"
           data-show-pagination-switch="true" data-show-refresh="true"
           data-show-toggle="true"
           data-resizable="true"
           data-toolbar="#toolbar">
      <thead>
      <tr>
        <th>Name</th>
        <th>VLAN ID</th>
        <th>Status</th>
        <th>Location</th>
        <th>Actions</th>
      </tr>
      </thead>

      <tbody>

      {% for obj in object_list %}
        <tr>

          <td> {{ obj.name }}</td>

          <td>
            <a href="{% url 'ip_manager:detail_vlan' obj.pk %}">
              {{ obj.vid }}
            </a>
          </td>

          <td> {{ obj.Status }}</td>
          <td> {{ obj.location }}</td>

          <td>
            <a href="{% url 'ip_manager:update_vlan' obj.pk %}"><i class="fa fa-edit"></i></a>
            &nbsp;&nbsp;
            <a href="{% url 'ip_manager:delete_vlan' obj.pk %}"><i class="fa fa-trash"></i></a>
          </td>

        </tr>

      {% endfor %}


      </tbody>
    </table>

  </div>

{% endblock content %}